name: test

on: [push, pull_request]

env:
  PUBLIC_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnuudUKwp+pM/2mjnLmVZcKyJmV/CZ63mo+q2XDxeAaC5etpLvhxtOoffDHtz4EyafWjy8E3n1zwBb/xq0j97ubGn3U5ymK4dTU6jtM5nqhv1XYMzh43W52GndMcKScWiPW3ddeDjwxPYfFIYoSckpRVkftifz9ADsWl7fkoabX0kZqq+kbTxeNEbJwtqdSl9VXYleJdhRH8D1+qUySh5STeCPxE15szjwvOEC2br3wa8uqZbna0xYLJXIeGog9HwTpVq5juC8Xs80qDgGJJ0S1pU6LjeQKYtpwIw1gV7iUsZd9c6uIXdetsCxX5SuniMGAjFv+MenYYOju2DQoDBSL2rYgkDWKjpVGaubRPVArFtNzK5F5Y22gAMWSOt+n0wixtmxs7qYK2kcCFjFUQH196hTNjGJaHPKfGh9FAgG8ZTpkWPd+U4RzvMWHIcZo7pp7iUgK7U36BDsnoFJLCfsa6xMeltWnn0HvCyvi2Hfu7Sy4ohaAoOyVswtBJnll3k= tofandel@Tofandel"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Port ${{matrix.port}}, User ${{matrix.user_name}}, Pass ${{matrix.user_pass}}, Sudo ${{matrix.sudo_access}}

    strategy:
      matrix:
        node_version: ['16.x']
        port: [22, 2222]
        user_name: ['root', 'my-user']
        user_pass: ['verys3cr3t!', null]
        sudo_access: ['true', 'false']
        hostname: ['dev.com']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Shutdown Ubuntu SSH (SUDO)
      run: sudo service ssh stop

    - name: Set up SSH
      uses: tofandel/ssh-server-action@master
      with:
        hostname: ${{ matrix.hostname }}
        port: ${{ matrix.port }} # Optional, default value is 22. The exposed ssh port
        user_name: ${{ matrix.user_name }} # Optional, default value is ssh-user
        user_password: ${{ matrix.user_pass }} # Optional
        sudo_access: ${{ matrix.sudo_access }} # Optional, allow user to use sudo without password, default: false
        public_key: $PUBLIC_KEY # Optional, Public key authorized to access the server
        public_key_url: https://github.com/Tofandel.keys # Optional, url to retrieve the public key

    - name: npm install, build, and test
      run: |
        yarn install --frozen-lockfile
        yarn lint
        echo "${{ secrets.ssh_private_key}}" > private-key.rsa
        yarn test --port=${{ matrix.port }} --username=${{ matrix.user_name }} --private-key=private-key.rsa --password=${{ matrix.user_pass }} --sudo=${{ matrix.sudo_access }} --hostname=${{ matrix.hostname }}
      env:
        CI: true
